# Project information
site_name: rms/docs
site_url: https://rmscode.github.io/MyDocs/
site_author: Ricky Saull
site_description: >-
  My personal documentation and note keeping site related to my work in IT.

# Repository
repo_name: GitHub
repo_url: https://github.com/rmscode/MyDocs
#edit_uri: edit/main/docs/

# Copyright
#copyright: Copyright &copy; 2023 Ricky Saull

# Material theme configuration
theme:
  name: material
  icon:
    logo: material/note-edit-outline
  features:
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    # - navigation.prune
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
  palette:
    scheme: slate
    primary: black
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

# Extra CSS
extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - search
  - offline
  - blog:
      authors: true
  #- encryptcontent
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: America/New_York
      exclude:
        - index.md
        - notes/*
  - git-latest-changes:
      limit_to_docs_dir: True
      repo_vendor: github
      enabled_on_serve: True
      history_limit: 10
  - mkdocs-audio

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated

# Extensions
markdown_extensions:
  - toc:
      permalink: "⚓︎"
      permalink_title: "Direct link"
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  #- pymdownx.smartsymbols
  - abbr
  - admonition
  - def_list
  - attr_list
  - md_in_html
  - footnotes

# Page tree
nav:
  - Home: index.md
  - General:
    - general/index.md
    - Cheat Sheets:
      - Git Cheat Sheet: general/cheat-sheets/git-cheat-sheet.md
      - Linux Cheat Sheet: general/cheat-sheets/linux-cheat-sheet.md
    - Guides:
      - Conference Kiosk: general/guides/linux-conference-machine.md
      - RDP Thin Client: general/guides/remmina-thin-client.md
    - Change Management: general/change-management.md
    - Continuous Availability: general/continuous-availability.md
    - Linux Directory Structure: general/linux-directory-structure.md
    - RAID: general/raid.md
    - ReFS vs NTFS: general/refs-vs-ntfs.md
    - Storage Snapshot: general/storage-snapshots.md
    - Windows Susbsystem for Linux: general/wsl.md
  - Hardware: 
    - hardware/index.md
    - Dell EMC:
      - PowerSwitch S4048-ON:
        - Overview: hardware/dell-emc/S4048-ON/overview.md
        - OS9:
          - Getting Started: hardware/dell-emc/S4048-ON/os9-getting-started.md
          - CLI Fundamentals: hardware/dell-emc/S4048-ON/os9-cli-fundamentals.md
          - Access Control Lists: hardware/dell-emc/S4048-ON/os9-acls.md
          - Debugging and Diagnostics: hardware/dell-emc/S4048-ON/os9-debugging.md
          - File Management: hardware/dell-emc/S4048-ON/os9-file-management.md
          - Logging: hardware/dell-emc/S4048-ON/os9-logging.md
          - Managing Access to Terminal Lines: hardware/dell-emc/S4048-ON/os9-tty-access.md
          - Uplink Failure Detection: hardware/dell-emc/S4048-ON/os9-ufd.md
          - Virtual Link Trunking (VLT): hardware/dell-emc/S4048-ON/os9-vlt.md
          - VLAN Configurations: hardware/dell-emc/S4048-ON/os9-vlan.md
          - Other: hardware/dell-emc/S4048-ON/os9-other.md
        - OS10: hardware/dell-emc/S4048-ON/os10.md
      - PowerVault ME4 Storage:
        - Overview: hardware/dell-emc/powervault-me4/me4-overview.md
        - Getting Started:
          - Deployment Brief: hardware/dell-emc/powervault-me4/me4-deployment-brief.md
          - System and Storage Setup: hardware/dell-emc/powervault-me4/me4-guided-setup.md
          - Host Setup (Windows): hardware/dell-emc/powervault-me4/me4-host-setup.md
          - Security Certificate (Optional): hardware/dell-emc/powervault-me4/me4-install-certificate.md
          - System Notifications (Optional): hardware/dell-emc/powervault-me4/me4-notifications.md
        - System Concepts:
          - Hosts and Initiators: hardware/dell-emc/powervault-me4/me4-hosts.md
          - Mappings: hardware/dell-emc/powervault-me4/me4-mappings.md
          - Pools and Disk Groups: hardware/dell-emc/powervault-me4/me4-pools.md
          - Replication: hardware/dell-emc/powervault-me4/me4-replication.md
          - Snapshots: hardware/dell-emc/powervault-me4/me4-snapshots.md
          - Spares (Parity Disks): hardware/dell-emc/powervault-me4/me4-spares.md
          - Virtual and Linear Storage: hardware/dell-emc/powervault-me4/me4-virtual-linear-storage.md
          - Volumes and Volume Groups: hardware/dell-emc/powervault-me4/me4-volumes.md
        - System Maintenance:
          - Firmware Updates: hardware/dell-emc/powervault-me4/me4-firmware-updates.md
          - Shutting Down a Controller Module: hardware/dell-emc/powervault-me4/me4-shutdown-controller.md
          - Module Removal & Replacement: hardware/dell-emc/powervault-me4/me4-module-removal.md
        - Accessing the CLI: hardware/dell-emc/powervault-me4/me4-cli.md
        - Logging: hardware/dell-emc/powervault-me4/me4-logging.md
        - Troubleshooting: hardware/dell-emc/powervault-me4/me4-troubleshooting.md
        - Best Practices: hardware/dell-emc/powervault-me4/me4-best-practice.md
      - PowerVault ME5 Storage:
        - Overview: hardware/dell-emc/powervault-me5/me5-overview.md
        - Getting Started:
          - Deployment Brief: hardware/dell-emc/powervault-me5/me5-deployment-brief.md
          - System and Storage Setup: hardware/dell-emc/powervault-me5/me5-guided-setup.md
          - Host Setup (Windows): hardware/dell-emc/powervault-me5/me5-host-setup.md
          - Security Certificate (Optional): hardware/dell-emc/powervault-me5/me5-install-certificate.md
          - System Notifications (Optional): hardware/dell-emc/powervault-me5/me5-notifications.md
        - System Concepts:
          - Hosts and Initiators: hardware/dell-emc/powervault-me5/me5-hosts.md
          - Pools and Disk Groups: hardware/dell-emc/powervault-me5/me5-pools.md
          - Replication: hardware/dell-emc/powervault-me5/me5-replication.md
          - Snapshots: hardware/dell-emc/powervault-me5/me5-snapshots.md
          - Spares (Parity Disks): hardware/dell-emc/powervault-me5/me5-spares.md
          - Virtual and Linear Storage: hardware/dell-emc/powervault-me5/me5-virtual-linear-storage.md
          - Volumes and Volume Groups: hardware/dell-emc/powervault-me5/me5-volumes.md
        - System Maintenance:
          - Firmware Updates: hardware/dell-emc/powervault-me5/me5-firmware-updates.md
          - Shutting Down a Controller Module: hardware/dell-emc/powervault-me5/me5-shutdown-controller.md
          - Module Removal & Replacement: hardware/dell-emc/powervault-me5/me5-module-removal.md
        - Accessing the CLI: hardware/dell-emc/powervault-me5/me5-cli.md
        - Logging: hardware/dell-emc/powervault-me5/me5-logging.md
        - Troubleshooting: hardware/dell-emc/powervault-me5/me5-troubleshooting.md
        - Best Practices: hardware/dell-emc/powervault-me5/me5-best-practice.md
    - Displays:
      - TVs: hardware/display/tv.md
    - Microsoft:
      - Microsoft Surface: hardware/microsoft/surface-rt.md
    - Panasonic:
      - Toughpad: hardware/panasonic/toughpad.md
    - Printers & Copiers:
      - Copiers: hardware/printers-copiers/copiers.md
      - Printers: hardware/printers-copiers/printers.md
    - Raspberry Pi:
      - Overview: hardware/raspberry-pi/overview.md
      - Hardening: hardware/raspberry-pi/hardening.md
      - Hardware Watchdog: hardware/raspberry-pi/hardware-watchdog.md
      - VNC: hardware/raspberry-pi/vnc.md
    - UPS Systems:
      - General: hardware/ups/general.md
      - CyberPower: hardware/ups/cyberpower.md
    - VOIP Phones: 
      - Fanvil V64: hardware/voip-phones/fanvil.md
      - Yealink: hardware/voip-phones/yealink.md
  - Networking: 
    - networking/index.md
    - Link Aggregation & LACP Basics: networking/link-aggregation.md
    - Understanding Network Infrastructure: networking/network-infrastructure.md
    - Spanning Tree Protocol: networking/spanning-tree.md
    - Subnetting: networking/subnetting.md
    - Wi-Fi: networking/wifi.md
  - Servers:
    - servers/index.md
    - Windows Server:
      - Active Directory & Domain Services:
        - Overview: servers/windows-server/active-directory/active-directory.md
      #- Data Deduplication: servers/windows-server/dedup.md
      - Failover Clustering:
        - Overview: servers/windows-server/msft-cluster.md
      - Group Policy:
        - Overview: servers/windows-server/group-policy/overview.md
        - Processing Order and Precedence: servers/windows-server/group-policy/processing-and-precedence.md
        - Managing GPOs: servers/windows-server/group-policy/managing.md
        - Preferences: servers/windows-server/group-policy/preferences.md
        - Security Filtering: servers/windows-server/group-policy/security-filtering.md
        - Troubleshooting: servers/windows-server/group-policy/troubleshooting.md
        - Best Practices: servers/windows-server/group-policy/best-practices.md
      #- MABS: servers/windows-server/mabs.md
      - Rearm Trial: servers/windows-server/rearm-trial.md
    - Linux Servers:
      - NetBox: servers/linux-servers/netbox.md
  - Software: 
    - software/index.md
    - LibreOffice:
      - Impress: software/libre-office/impress.md
    - Microsoft 365:
      - Exchange Hybrid Deployment: software/microsoft-365/hybrid-exchange.md
      - Teams: software/microsoft-365/teams/ms-teams.md
      - Teams Phone: software/microsoft-365/teams/ms-teams-phone.md
    - Microsoft Office:
      - Outlook: software/microsoft-office/outlook/outlook.md
      - Word:
        - Hide Images: software/microsoft-office/word/hide-images.md
    - MkDocs:
      - Getting Started: software/mkdocs/getting-started.md
      - Creating Your Site: software/mkdocs/creating-site.md
      - Publishing Your Site: software/mkdocs/publishing.md
    - Operating Systems:
      - Linux:
        - General: software/operating-systems/linux/general.md
        - DietPi: software/operating-systems/linux/dietpi.md
        - PiSignage: software/operating-systems/linux/pisignage.md
      - Windows: 
        - General: software/operating-systems/windows/windows.md
    - ALSA: software/alsa.md
    - Git: software/git.md
    - Hyper-V: software/hyper-v.md
    - Notepad++: software/notepadpp.md
    - PulseAudio: software/pulse-audio.md
    - Quick Assist: software/quick-assist.md
    - Remote Desktop: software/remote-desktop.md
    - Remmina: software/remmina.md
    - Uhubctl: software/uhubctl.md
    - Zoom: software/zoom.md
  - SOP: 
    - sop/index.md
  - Notes:
    - notes/index.md
    - Daily Work Log: notes/2025.md
    - Work Log Archive: 
      - 2024: notes/2024.md
      - 2023: notes/2023.md
  - Archives: 
    - archives/index.md
    - Hardware: archives/hardware-archive.md
