site_name: My Docs

## Navbar options
nav:
  - Home: index.md
  - General: general/general.md
  - Hardware: hardware/hardware.md
  - Networking: networking/networking.md
  - Software: software/software.md
  - SOP: sop/SOP.md
  - Notes: 
    - Notes: notes/notes.md
    - 2023: notes/2023.md
    - Server Research 2023: notes/ServerResearch2023.md
    - Archive: notes/archive.md

## Theme options
theme:
  name: material

  palette:
    scheme: slate

  #font:
    #text: Fira Code

  navigation_depth: 2
  locale: en
  highlightjs: true
  prev_next_buttons_location: both

  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    #- navigation.sections
    - toc.follow
    - toc.nested
    - toc.integrate
    - navigation.prune
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate

  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s

# Markdown extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: "#"
      toc_depth: 3
  - abbr
  - admonition
  - def_list

# Plugins
plugins:
  - search
  #- blog
  - offline
  