site_name: My Docs

## Navbar options
nav:
  - Home: index.md
  - General: general/general.md
  - Hardware: hardware/hardware.md
  - Networking: networking/networking.md
  - Software: software/software.md
  - SOP: sop/SOP.md
  - Notes: 
    - Notes: notes/notes.md
    - '2023': notes/2023.md

## Theme options
theme:
  name: material

  palette:
    scheme: slate

  #font:
    #text: Fira Code

  navigation_depth: 2
  locale: en
  highlightjs: true
  prev_next_buttons_location: both
  #logo: MarkdownImages/NEPLogo.png

  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - toc.follow
    - toc.nested
    - toc.integrate
    - navigation.prune
    - navigation.indexes

  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s

# Markdown extensions
markdown_extensions:
  - toc:
      permalink: "#"
      toc_depth: 2

# Plugins
plugins:
  - search
  #- blog
  - offline
