# Project information
site_name: rms/docs
site_url: https://rmscode.github.io/MyDocs/
site_author: Ricky Saull
site_description: >-
  My personal documentation and note keeping site related to my work in IT.

# Repository
repo_name: GitHub
repo_url: https://github.com/rmscode/MyDocs
#edit_uri: edit/main/docs/

# Copyright
#copyright: Copyright &copy; 2023 Ricky Saull

# Material theme configuration
theme:
  name: material
  icon:
    logo: material/note-edit-outline
    tag:
      notes: material/notebook-edit
      docs: material/file-document-multiple
  features:
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    # - navigation.prune
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
  palette:
    scheme: slate
    primary: black
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

# Extra CSS
extra_css:
  - assets/css/extra.css

# Plugins
plugins:
  - search
  - offline
  - meta:
      enabled: true
  #- encryptcontent
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: America/New_York
      exclude:
        - index.md
        - notes/20**.md
  - git-latest-changes:
      limit_to_docs_dir: True
      timestamp_format: "%m.%d.%Y %H:%M"
      repo_vendor: github
      enabled_on_serve: True
      history_limit: 5
      table_features:
        - "page_path_link"
        - "timestamp"
        - "author"
        - "message"
  - mkdocs-audio
  # - tags
  - autolinks

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  # tags:
  #   Documentation: docs
  #   Hardware: hardware
  #   Networking: networking
  #   Notes: notes
  #   Software: software
  #   Standard Operating Procedures: sop

# Extensions
markdown_extensions:
  - toc:
      permalink: "⚓︎"
      permalink_title: "Direct link"
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  #- pymdownx.smartsymbols
  - abbr
  - admonition
  - def_list
  - attr_list
  - md_in_html
  - footnotes

# Configuration Inheritance
INHERIT: ./nav.yml