# Project information
site_name: My Docs
site_url: https://rmscode.github.io/MyDocs/
site_author: Ricky Saull
site_description: >-
  My personal documentation and note keeping site related to my work in IT.

# Repository
repo_name: rmscode/MyDocs
repo_url: https://github.com/rmscode/MyDocs
#edit_uri: edit/main/docs/

# Copyright
#copyright: Copyright &copy; 2023 Ricky Saull

# Material theme configuration
theme:
  name: material
  features:
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - navigation.tracking
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.path
    - navigation.top
    # - navigation.prune
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    # - toc.integrate
  palette:
    scheme: slate

# Plugins
plugins:
  - search
  - offline
  #- encryptcontent
  - git-revision-date-localized:
      enable_creation_date: true

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: "⚓︎"
      permalink_title: "Anchor link to this section for reference"
      toc_depth: 3
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - abbr
  - admonition
  - def_list
  - attr_list
  - md_in_html

# Page tree
nav:
  - Home: index.md
  - General: 
    - general/index.md
  - Hardware: 
    - hardware/index.md
    - Dell EMC: 
      - hardware/dell-emc/s4048-on.md
      - hardware/dell-emc/powervault-me4-draft.md
  - Networking: 
    - networking/index.md
  - Software: 
    - software/index.md
    - Windows Server: software/windows-server.md
  - SOP: 
    - sop/index.md
  - Notes: 
    - notes/index.md
    - 2023: notes/2023.md
    - Server Research 2023: notes/ServerResearch2023.md
    - Archive: notes/archive.md
