site_name: My Docs

## Navbar options
nav:
  - Home: index.md
  - General: 
    - general/index.md
  - Hardware: 
    - hardware/index.md
    - Dell EMC: hardware/dell-emc.md
    - PowerVault ME4 (WIP): hardware/powervault-me4-draft.md
  - Networking: 
    - networking/index.md
  - Software: 
    - software/index.md
    - Windows Server: software/windows-server.md
  - SOP: 
    - sop/index.md
  - Notes: 
    - notes/index.md
    - 2023: notes/2023.md
    - Server Research 2023: notes/ServerResearch2023.md
    - Archive: notes/archive.md

## Theme options
theme:
  name: material

  palette:
    scheme: slate

  #font:
    #text: Fira Code

  navigation_depth: 3
  locale: en
  highlightjs: true
  prev_next_buttons_location: both

  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - toc.follow
    - toc.nested
    - toc.integrate
    - navigation.prune
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate

  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s

# Markdown extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: "#"
      toc_depth: 3
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - abbr
  - admonition
  - def_list
  - attr_list
  - md_in_html

# Plugins
plugins:
  - search
  - offline
  - encryptcontent
  - blog
