# Project information
site_name: My Docs
site_url: https://rmscode.github.io/MyDocs/
site_author: Ricky Saull
site_description: >-
  My personal documentation and note keeping site related to my work in IT.

# Repository
repo_name: rmscode/MyDocs
repo_url: https://github.com/rmscode/MyDocs
#edit_uri: edit/main/docs/

# Copyright
#copyright: Copyright &copy; 2023 Ricky Saull

# Material theme configuration
theme:
  name: material
  features:
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    # - navigation.prune
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    # - toc.integrate
  palette:
    scheme: slate
    primary: black
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - search
  - offline
  #- encryptcontent
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: America/New_York
      exclude:
        - index.md
        - notes/*

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "⚓︎"
      permalink_title: "Anchor link to this section for reference"
      toc_depth: 3
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - abbr
  - admonition
  - def_list
  - attr_list
  - md_in_html

# Page tree
nav:
  - Home: index.md
  - General: 
    - general/index.md
    - general/wsl.md
    - Cheat Sheets:
      - general/linux-cheat-sheet.md
  - Hardware: 
    - hardware/index.md
    - Dell EMC: 
      - PowerSwitch S4048-ON:
        - hardware/dell-emc/S4048-ON/overview.md
        - OS9:
          - hardware/dell-emc/S4048-ON/os9.md
          - hardware/dell-emc/S4048-ON/os9-debugging.md
          - hardware/dell-emc/S4048-ON/os9-file-management.md
          - hardware/dell-emc/S4048-ON/os9-logging.md
          - hardware/dell-emc/S4048-ON/os9-tty-access.md
          - hardware/dell-emc/S4048-ON/os9-ufd.md
          - hardware/dell-emc/S4048-ON/os9-vlan.md
          - hardware/dell-emc/S4048-ON/os9-vlt.md
          - hardware/dell-emc/S4048-ON/os9-other.md
        - OS10:
          - hardware/dell-emc/S4048-ON/os10.md
      - PowerVault ME4 Storage:
        - hardware/dell-emc/powervault-me4/me4-overview.md
        - Getting Started:
          - hardware/dell-emc/powervault-me4/me4-deployment-brief.md
          - hardware/dell-emc/powervault-me4/me4-guided-setup.md
          - hardware/dell-emc/powervault-me4/me4-host-setup.md
        - System Concepts:
          - hardware/dell-emc/powervault-me4/me4-pools.md
          - hardware/dell-emc/powervault-me4/me4-disk-groups.md
          - hardware/dell-emc/powervault-me4/me4-virtual-linear-storage.md
        - System Maintenance:
          - hardware/dell-emc/powervault-me4/me4-firmware-updates.md
          - hardware/dell-emc/powervault-me4/me4-shutdown-controller.md
          - hardware/dell-emc/powervault-me4/me4-module-removal.md
        - hardware/dell-emc/powervault-me4/me4-cli.md
        - hardware/dell-emc/powervault-me4/me4-logging.md
        - hardware/dell-emc/powervault-me4/me4-troubleshooting.md
        - hardware/dell-emc/powervault-me4/me4-best-practice.md
    - Microsoft:
      - hardware/microsoft/surface-rt.md
    - hardware/raspberrypi.md
  - Networking: 
    - networking/index.md
    - networking/link-aggregation.md
    - networking/network-infrastructure.md
    - networking/spanning-tree.md
  - Servers:
    - servers/msft-cluster.md
  - Software: 
    - software/index.md
    - software/outlook.md
    - software/pisignage.md
    - Windows Server OS: 
      - software/windows-server/index.md
      - software/windows-server/active-directory.md
      - software/windows-server/dedup.md
      - software/windows-server/group-policy.md
  - SOP: 
    - sop/index.md
  - Troubleshooting:
    - troubleshooting/msft-cluster-trouble.md
    - troubleshooting/hyper-v-trouble.md
  - Notes: 
    - notes/index.md
    - 2024: notes/2024.md
    - 2023: notes/2023.md
    - Server Research 2023: notes/ServerResearch2023.md
